# Generated by Django 2.2.2 on 2019-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('start_date', models.DecimalField(decimal_places=0, max_digits=6)),
                ('status', models.CharField(max_length=7)),
                ('school', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
