# Generated by Django 2.2.2 on 2019-06-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='status',
            field=models.CharField(max_length=6),
        ),
    ]
