# Generated by Django 2.2.2 on 2019-06-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190628_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='status',
            field=models.CharField(max_length=8),
        ),
    ]
