# Generated by Django 2.2.2 on 2019-07-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190628_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('start_date', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Début expérience')),
                ('end_date', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Fin expérience')),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
